### ISSUE TITLE
Nodeselector

### ISSUE THREAD

**Issue by vivekk123** [Cloudneeti/helm-charts#16]
Hi,

We want to use this chart for hybrid clusteres (windows and linux nodes). The problem is that the current nodeSelector allows pods to be deployed to windows nodes, which leads to ImagePullBackOff.

Can the current nodeSelector be changed 

from
```
          nodeSelector:
            node-role.kubernetes.io/master: ""
```

to
```
          nodeSelector:
            node-role.kubernetes.io/master: ""
            kubernetes.io/os: linux
```

Thanks :)

**Comment by eoq** [comment]
Thanks Vivek for opening this issue.
I tested this change in our AKS environment with hybrid node pools and it would not schedule the job with the node-role.kubernetes.io/master selector. We are not AKS-Engine in any case so I added an `else if` for AKS with just the /os selector set to linux and it works. See the snippet below. Let me know if I should do a PR or share something else.
Thanks
Ed

>          {{ else if eq "AKS" .Values.clusterHosting }}
>          nodeSelector:
>              kubernetes.io/os: linux

**Comment by vivekk123** [comment]
@ankitsrao Hi 
Is it possible to make the adjustments mentioned above  :)?

**Comment by ankitsrao** [comment]
Hi @vivekk123 ,

Thank you for opening this issue and apologies for the delayed response.
We will have the suggestion by @eoq verified and accomodate the changes if it passes all required check, in the future releases.

Thanks

**Comment by rahulkhengare** [comment]
Added enhancement to chart 0.13.0 version.
Thank you @vivekk123 and @eoq for raising this.

**Comment by eoq** [comment]
Thanks everyone!
Ed
